### ISSUE TITLE
SSH key is always destroyed & recreated

### ISSUE THREAD

**Issue by hazcod** [terraform-providers/terraform-provider-scaleway#226]
The scaleway SSH public key resource is always destroyed & recreated on plan/apply.

### Terraform Version
```
Terraform v0.12.6
+ provider.scaleway v1.10.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- scaleway_ssh_key

### Terraform Configuration Files
```hcl

variable "ssh_public_key_path" {
  default = "ssh.pub"
}

resource "scaleway_ssh_key" "scaleway_ssh_public_key" {
    key = "${file("${var.ssh_public_key_path}")}"
}
```

### Debug Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.scaleway.scaleway_ssh_key.scaleway_ssh_public_key must be replaced
-/+ resource "scaleway_ssh_key" "scaleway_ssh_public_key" {
      ~ id  = "00:d1:ff:df:11:23:f8:24:8a:5a:65:05:19:00:00:00" -> (known after apply)
      ~ key = <<~EOT # forces replacement
            ssh-rsa XXKSLDLDJSKJ xxx@xxx
        EOT
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior
Key left untouched.

### Actual Behavior
Key is destroyed and recreated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
n/a

### References
https://github.com/ironPeakServices/infrastructure/blob/master/modules/scaleway/main.tf#L29

**Comment by QuentinBrosse** [comment]
Hi @hazcod,

## Explaining

What you're seeing here is a result of the fact that the `file()` function isn't evaluated until the apply step. The reason is that Terraform can't predict if the content of the file will change when you subsequently apply the plan.

## Two solutions to fix the issue

### 1. Set the SSH public key itself in the variable and not the path of the file

With this configuration, Terrfarom will know the exact value of the SSH key at the plan time. It is your responsibility to don't change this variable during the plan and the apply phases.

```tf
variable "ssh_public_key" {
  default = "test.pub"
}

resource "scaleway_ssh_key" "scaleway_ssh_public_key" {
  key = var.ssh_public_key
}
```

```sh
$ terraform plan -var="ssh_public_key=<YOUR-SSH-PUBLIC-KEY>"
```
Note that your can also use an [env variable](https://www.terraform.io/docs/configuration/variables.html#environment-variables).

### 2. Ignore changes

Use the [`lifecycle.ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) meta-arguments to cause Terraform to ignore future changes to the value.

```tf
resource "scaleway_ssh_key" "scaleway_ssh_public_key" {
  lifecycle {
    ignore_changes = [
      "key"
    ]
  }
  key = file(var.ssh_public_key_path)
}
```

Hopping it helped! :)

**Comment by hazcod** [comment]
@QuentinBrosse thank you for the explanation!
