### ISSUE TITLE
Unable to delete Kapsule default pool

### ISSUE THREAD

**Issue by foux** [terraform-providers/terraform-provider-scaleway#374]
### Terraform Version
```
Terraform v0.12.18
+ provider.scaleway v1.13.0
```

### Affected Resource(s)
- scaleway_k8s_cluster_beta

### Terraform Configuration Files
```hcl
resource "scaleway_k8s_cluster_beta" "cluster" {
    cni           = "cilium"
    name          = "cluster"
    region        = "fr-par"
    tags          = [ "kube"]
    version       = "1.17.0"
}
```

### Debug Output
```
Error: "default_pool": required field is not set

  on scaleway.tf line 3, in resource "scaleway_k8s_cluster_beta" "cluster":
   3: resource "scaleway_k8s_cluster_beta" "cluster" {
```

### Expected Behavior
We should be able to delete the default pool, if we're using another one

### Actual Behavior
We can't delete the default pool, even though we can from the API/web interface

### Steps to Reproduce
1. `terraform apply`

**Comment by debovema** [comment]
Hello

I am not sure whether this fix allows to create a *scaleway_k8s_cluster_beta* resource without any default pool if a *scaleway_k8s_pool_beta* is created and assigned to the cluster elsewhere.

I tested with *master* version and it does not work. However I think it should be the expected behaviour, don't you think ?

**Comment by Sh4d1** [comment]
Hey @debovema !
You can't create a cluster without a default pool. It's an API limitation. I think it would be kind of hard to mimic such feature on Terraform. So my guess it's that it's going to stay like this (and stay coherent with the API).
