### ISSUE TITLE
Don't remove SecurityGroup Rule flexibilty for v2

### ISSUE THREAD

**Issue by reversTeam** [terraform-providers/terraform-provider-scaleway#381]
Hi Scaleway team,

I am currently using version 1.13 of the scaleway provider for terraform. I see that version 2 is in preparation but when I look at the methods exposed by this one I realize that some essential functionality has the configuration of SecurityGroup for me will not be supported.

I had opened an issue not long ago to ask if you were going to add the possibility of putting several SecurityGroups on a single instance, the idea was to create some by service and to add SecurityGroups on the machines that host Services. It was not in your roadmap I had to find another way to implement this functionality.
Suddenly I went through the `security_group_rule` which offers me the possibility of configuring rules on my securityGroup post creation, when I know the ips of the instances and their services to open or close the routes. My instances `drop` everything by default, I only open the necessary.

The problem is that I see that this method will not be supported for v2, on top of that we cannot add a securityGroup to an instance outside of the instance creation process. This citation makes it impossible for me to properly configure my network with default drop rules.
When I provision my instance, I do not know its ip and if it is linked with another instance I could not add the resulting rules, because the securityGroup is immutable.

Actualy v1.13:
 1. Create all SecurityGroup with empty rules (drop by default)
 2. Create all Instance (link with empty SecurtyGroup)
 3. Configure all rules in all SecurityGroup

v2.0:
 1. Create all SecurityGroup (cannot config with the final private IP)
 2. Create all Instance (link with SecurityGroup)
 3. Cannnot configure rules in SecurityGroup, because `scaleway_security_group_rule` is not availabled

Solution 1: Multi Security Group
 1.0 Create Instance (without securityGroup)
 1.1 Create SecurityGroup
 2.  Add securityGroups to instance (after creation)
Note: I don't need to add rules to the SecurityGroup, if I can put several SecurityGroups on a single instance

Solution 2: Conserve the add rule like actually
 1. Create all SecurityGroup with empty rules (drop by default)
 2. Create all Instance (link with empty SecurtyGroup)
 3. Configure all rules in all SecurityGroup

For the best:
 - Conserve the `scaleway_security_group_rule` feature in the v2 (the name/scope is not important, can change)
 - Implemented add SecurityGroups and can adding SecurityGroup(s) after instance creation

Happy New Year everyone,
Thank you

**Comment by jerome-quere** [comment]
Hi @reversTeam,

Thank you for your descriptive issue.
I discussed it with the team and here are our thoughts and proposed solution.

- `scaleway_security_group_rule` approach as a major issue when it comes to ordering. In some cases rule ordering might be crucial and it will be very hard to guarantee order when rules are split across multiple resources due to the way terraform handle resource (a resource is not aware of other resources)
- A security group composition cannot be handled in terraform directly without support from the instance API which is not planned at all.

After discussing it we found the following solution that solves your circular dependency issue. ensures order if needed and is backward compatible.

```
resource scaleway_instance_server s01 { 
   security_group_id = scaleway_instance_segurity_group.sg1.id
}

resource scaleway_instance_segurity_group sg01 {
   external_rules = true // When set to true resource delegate reule management to scaleway_instance_segurity_group_rules
}

resource scaleway_instance_segurity_group_rules sg01 {
   security_group_ip = scaleway_instance_segurity_group.sg01.id

    // keeping rules in a list makes it possible to guarantee order
   inbound_rule { 
     address = scaleway_instance_server.s01.private_ip 
   }
}
```

This issue has been added to our backlog and we will make sure to link this issue in our PR.
