### ISSUE TITLE
Re-created scaleway_ip is not attached to initial server

### ISSUE THREAD

**Issue by mtarnovan** [terraform-providers/terraform-provider-scaleway#40]
Hi there,

I'm using Terraform v0.11.3 with provider.scaleway v1.0.1. I have a scaleway_server which was created with a scaleway_ip attached, like so:

```tf
resource "scaleway_ip" "foo" {}

resource "scaleway_server" "bar" {
   ...
   public_ip      = "${scaleway_ip.dokku_node_ip.ip}"
   ...
```

If I manually taint the IP and run `apply`, the IP does not get reattached to the instance. Is this expected behaviour? 

I noticed I could do something like this:

```tf
resource "scaleway_ip" "foo" {
  server = "${scaleway_server.bar.id}"
}

resource "scaleway_server" "bar" {
```

In this case I'm not sure what the direction of the dependency graph between the ip and the instance is / should be, and if I still need to declare it in the `scaleway_server` block as `public_ip`

Thanks

**Comment by nicolai86** [comment]
Hey @mtarnovan ,

thank you for the question.

In the first example, the IP attachment is only evaluated on server creation time. Tainting the ip does not modify the server, because the server doesn't know about this change. 

If you want to modify the server when you taint the ip you should reference the server on the ip, as done in the second example. 

In my eyes the first approach only exists for compatibility reasons, I'll look into deprecating it.

**Comment by mtarnovan** [comment]
Hi @nicolai86, a quick follow-up question please:

I have inverted the dependency like in the 2nd example above:
```tf
resource "scaleway_ip" "foo" {
  server = "${scaleway_server.bar.id}"
}

resource "scaleway_server" "bar" {
```
...and now it looks like the server instantiation hangs. Do I need to add an explicit dependency on the IP in the server definition?

Thanks

**Comment by mtarnovan** [comment]
Also, I'm seeing this error:

```
Error: Error asking for user input: 2 error(s) occurred:

* Cycle: module.dokku.scaleway_server.dokku_node, module.dokku.scaleway_ip.dokku_node_ip
* Cycle: module.prom.scaleway_server.prom_node, module.prom.scaleway_ip.prom_node_ip
```

with these definitions:
```
resource "scaleway_ip" "dokku_node_ip" {
  server = "${scaleway_server.dokku_node.id}"
}
resource "scaleway_server" "dokku_node" {
...
  public_ip      = "${scaleway_ip.dokku_node_ip.ip}"
...
```

**Comment by nicolai86** [comment]
@mtarnovan the dependency cycle terraform mentions is because the server references the ip, and the ip references the server. You have to decide for one of them.

Referencing the server in the ip should lead to an ip update in taint. That being said if you use an image that requires a public ip to boot you might need to set public_ip to true to get one.
